# Imports

In [47]:
import mne
import mne.io
import numpy as np
import pandas as pd
import dill

from pathlib import Path

# Data Load

## OpenNeuro

In [49]:
eeg_file_path_format = 'openneuro_data/sub-{number:03}/eeg/sub-{number:03}_task-eyesclosed_eeg.set'

openneuro_X = pd.DataFrame()

for n in range(1, 66):
    file_path = eeg_file_path_format.format(number=n)
    raw = mne.io.read_raw_eeglab(file_path, preload=True)
    data = pd.Series(raw.to_data_frame().to_numpy().flatten()).iloc[:500*60]
    data.drop(data.index[data.index % 20 == 0], inplace=True)
    data = data.reset_index(drop=True)
    openneuro_X = pd.concat([openneuro_X, data.to_frame().T], ignore_index=True)

openneuro_X

C:\Users\Nathaniel Byrd\AppData\Local\Temp\ipykernel_45480\417584291.py:7: RuntimeWarning: The data contains 'boundary' events, indicating data discontinuities. Be cautious of filtering and epoching around these events.
  raw = mne.io.read_raw_eeglab(file_path, preload=True)
C:\Users\Nathaniel Byrd\AppData\Local\Temp\ipykernel_45480\417584291.py:7: RuntimeWarning: The data contains 'boundary' events, indicating data discontinuities. Be cautious of filtering and epoching around these events.
  raw = mne.io.read_raw_eeglab(file_path, preload=True)
C:\Users\Nathaniel Byrd\AppData\Local\Temp\ipykernel_45480\417584291.py:7: RuntimeWarning: The data contains 'boundary' events, indicating data discontinuities. Be cautious of filtering and epoching around these events.
  raw = mne.io.read_raw_eeglab(file_path, preload=True)
C:\Users\Nathaniel Byrd\AppData\Local\Temp\ipykernel_45480\417584291.py:7: RuntimeWarning: The data contains 'boundary' events, indicating data discontinuities. Be cautious of filtering and epoching around these events.
  raw = mne.io.read_raw_eeglab(file_path, preload=True)
C:\Users\Nathaniel Byrd\AppData\Local\Temp\ipykernel_45480\417584291.py:7: RuntimeWarning: The data contains 'boundary' events, indicating data discontinuities. Be cautious of filtering and epoching around these events.
  raw = mne.io.read_raw_eeglab(file_path, preload=True)
C:\Users\Nathaniel Byrd\AppData\Local\Temp\ipykernel_45480\417584291.py:7: RuntimeWarning: The data contains 'boundary' events, indicating data discontinuities. Be cautious of filtering and epoching around these events.
  raw = mne.io.read_raw_eeglab(file_path, preload=True)
C:\Users\Nathaniel Byrd\AppData\Local\Temp\ipykernel_45480\417584291.py:7: RuntimeWarning: The data contains 'boundary' events, indicating data discontinuities. Be cautious of filtering and epoching around these events.
  raw = mne.io.read_raw_eeglab(file_path, preload=True)
C:\Users\Nathaniel Byrd\AppData\Local\Temp\ipykernel_45480\417584291.py:7: RuntimeWarning: The data contains 'boundary' events, indicating data discontinuities. Be cautious of filtering and epoching around these events.
  raw = mne.io.read_raw_eeglab(file_path, preload=True)
C:\Users\Nathaniel Byrd\AppData\Local\Temp\ipykernel_45480\417584291.py:7: RuntimeWarning: The data contains 'boundary' events, indicating data discontinuities. Be cautious of filtering and epoching around these events.
  raw = mne.io.read_raw_eeglab(file_path, preload=True)
C:\Users\Nathaniel Byrd\AppData\Local\Temp\ipykernel_45480\417584291.py:7: RuntimeWarning: The data contains 'boundary' events, indicating data discontinuities. Be cautious of filtering and epoching around these events.
  raw = mne.io.read_raw_eeglab(file_path, preload=True)
C:\Users\Nathaniel Byrd\AppData\Local\Temp\ipykernel_45480\417584291.py:7: RuntimeWarning: The data contains 'boundary' events, indicating data discontinuities. Be cautious of filtering and epoching around these events.
  raw = mne.io.read_raw_eeglab(file_path, preload=True)
C:\Users\Nathaniel Byrd\AppData\Local\Temp\ipykernel_45480\417584291.py:7: RuntimeWarning: The data contains 'boundary' events, indicating data discontinuities. Be cautious of filtering and epoching around these events.
  raw = mne.io.read_raw_eeglab(file_path, preload=True)
C:\Users\Nathaniel Byrd\AppData\Local\Temp\ipykernel_45480\417584291.py:7: RuntimeWarning: The data contains 'boundary' events, indicating data discontinuities. Be cautious of filtering and epoching around these events.
  raw = mne.io.read_raw_eeglab(file_path, preload=True)
C:\Users\Nathaniel Byrd\AppData\Local\Temp\ipykernel_45480\417584291.py:7: RuntimeWarning: The data contains 'boundary' events, indicating data discontinuities. Be cautious of filtering and epoching around these events.
  raw = mne.io.read_raw_eeglab(file_path, preload=True)
C:\Users\Nathaniel Byrd\AppData\Local\Temp\ipykernel_45480\417584291.py:7: RuntimeWarning: The data contains 'boundary' events, indicating data discontinuities. Be cautious of filtering and epoching around these events.
  raw = mne.io.read_raw_eeglab(file_path, preload=True)
C:\Users\Nathaniel Byrd\AppData\Local\Temp\ipykernel_45480\417584291.py:7: RuntimeWarning: The data contains 'boundary' events, indicating data discontinuities. Be cautious of filtering and epoching around these events.
  raw = mne.io.read_raw_eeglab(file_path, preload=True)
C:\Users\Nathaniel Byrd\AppData\Local\Temp\ipykernel_45480\417584291.py:7: RuntimeWarning: The data contains 'boundary' events, indicating data discontinuities. Be cautious of filtering and epoching around these events.
  raw = mne.io.read_raw_eeglab(file_path, preload=True)
C:\Users\Nathaniel Byrd\AppData\Local\Temp\ipykernel_45480\417584291.py:7: RuntimeWarning: The data contains 'boundary' events, indicating data discontinuities. Be cautious of filtering and epoching around these events.
  raw = mne.io.read_raw_eeglab(file_path, preload=True)
C:\Users\Nathaniel Byrd\AppData\Local\Temp\ipykernel_45480\417584291.py:7: RuntimeWarning: The data contains 'boundary' events, indicating data discontinuities. Be cautious of filtering and epoching around these events.
  raw = mne.io.read_raw_eeglab(file_path, preload=True)
C:\Users\Nathaniel Byrd\AppData\Local\Temp\ipykernel_45480\417584291.py:7: RuntimeWarning: The data contains 'boundary' events, indicating data discontinuities. Be cautious of filtering and epoching around these events.
  raw = mne.io.read_raw_eeglab(file_path, preload=True)
C:\Users\Nathaniel Byrd\AppData\Local\Temp\ipykernel_45480\417584291.py:7: RuntimeWarning: The data contains 'boundary' events, indicating data discontinuities. Be cautious of filtering and epoching around these events.
  raw = mne.io.read_raw_eeglab(file_path, preload=True)
C:\Users\Nathaniel Byrd\AppData\Local\Temp\ipykernel_45480\417584291.py:7: RuntimeWarning: The data contains 'boundary' events, indicating data discontinuities. Be cautious of filtering and epoching around these events.
  raw = mne.io.read_raw_eeglab(file_path, preload=True)
C:\Users\Nathaniel Byrd\AppData\Local\Temp\ipykernel_45480\417584291.py:7: RuntimeWarning: The data contains 'boundary' events, indicating data discontinuities. Be cautious of filtering and epoching around these events.
  raw = mne.io.read_raw_eeglab(file_path, preload=True)
C:\Users\Nathaniel Byrd\AppData\Local\Temp\ipykernel_45480\417584291.py:7: RuntimeWarning: The data contains 'boundary' events, indicating data discontinuities. Be cautious of filtering and epoching around these events.
  raw = mne.io.read_raw_eeglab(file_path, preload=True)
C:\Users\Nathaniel Byrd\AppData\Local\Temp\ipykernel_45480\417584291.py:7: RuntimeWarning: The data contains 'boundary' events, indicating data discontinuities. Be cautious of filtering and epoching around these events.
  raw = mne.io.read_raw_eeglab(file_path, preload=True)
C:\Users\Nathaniel Byrd\AppData\Local\Temp\ipykernel_45480\417584291.py:7: RuntimeWarning: The data contains 'boundary' events, indicating data discontinuities. Be cautious of filtering and epoching around these events.
  raw = mne.io.read_raw_eeglab(file_path, preload=True)
C:\Users\Nathaniel Byrd\AppData\Local\Temp\ipykernel_45480\417584291.py:7: RuntimeWarning: The data contains 'boundary' events, indicating data discontinuities. Be cautious of filtering and epoching around these events.
  raw = mne.io.read_raw_eeglab(file_path, preload=True)
C:\Users\Nathaniel Byrd\AppData\Local\Temp\ipykernel_45480\417584291.py:7: RuntimeWarning: The data contains 'boundary' events, indicating data discontinuities. Be cautious of filtering and epoching around these events.
  raw = mne.io.read_raw_eeglab(file_path, preload=True)
C:\Users\Nathaniel Byrd\AppData\Local\Temp\ipykernel_45480\417584291.py:7: RuntimeWarning: The data contains 'boundary' events, indicating data discontinuities. Be cautious of filtering and epoching around these events.
  raw = mne.io.read_raw_eeglab(file_path, preload=True)
C:\Users\Nathaniel Byrd\AppData\Local\Temp\ipykernel_45480\417584291.py:7: RuntimeWarning: The data contains 'boundary' events, indicating data discontinuities. Be cautious of filtering and epoching around these events.
  raw = mne.io.read_raw_eeglab(file_path, preload=True)
C:\Users\Nathaniel Byrd\AppData\Local\Temp\ipykernel_45480\417584291.py:7: RuntimeWarning: The data contains 'boundary' events, indicating data discontinuities. Be cautious of filtering and epoching around these events.
  raw = mne.io.read_raw_eeglab(file_path, preload=True)
C:\Users\Nathaniel Byrd\AppData\Local\Temp\ipykernel_45480\417584291.py:7: RuntimeWarning: The data contains 'boundary' events, indicating data discontinuities. Be cautious of filtering and epoching around these events.
  raw = mne.io.read_raw_eeglab(file_path, preload=True)
C:\Users\Nathaniel Byrd\AppData\Local\Temp\ipykernel_45480\417584291.py:7: RuntimeWarning: The data contains 'boundary' events, indicating data discontinuities. Be cautious of filtering and epoching around these events.
  raw = mne.io.read_raw_eeglab(file_path, preload=True)
C:\Users\Nathaniel Byrd\AppData\Local\Temp\ipykernel_45480\417584291.py:7: RuntimeWarning: The data contains 'boundary' events, indicating data discontinuities. Be cautious of filtering and epoching around these events.
  raw = mne.io.read_raw_eeglab(file_path, preload=True)
C:\Users\Nathaniel Byrd\AppData\Local\Temp\ipykernel_45480\417584291.py:7: RuntimeWarning: The data contains 'boundary' events, indicating data discontinuities. Be cautious of filtering and epoching around these events.
  raw = mne.io.read_raw_eeglab(file_path, preload=True)
C:\Users\Nathaniel Byrd\AppData\Local\Temp\ipykernel_45480\417584291.py:7: RuntimeWarning: The data contains 'boundary' events, indicating data discontinuities. Be cautious of filtering and epoching around these events.
  raw = mne.io.read_raw_eeglab(file_path, preload=True)
C:\Users\Nathaniel Byrd\AppData\Local\Temp\ipykernel_45480\417584291.py:7: RuntimeWarning: The data contains 'boundary' events, indicating data discontinuities. Be cautious of filtering and epoching around these events.
  raw = mne.io.read_raw_eeglab(file_path, preload=True)
C:\Users\Nathaniel Byrd\AppData\Local\Temp\ipykernel_45480\417584291.py:7: RuntimeWarning: The data contains 'boundary' events, indicating data discontinuities. Be cautious of filtering and epoching around these events.
  raw = mne.io.read_raw_eeglab(file_path, preload=True)
C:\Users\Nathaniel Byrd\AppData\Local\Temp\ipykernel_45480\417584291.py:7: RuntimeWarning: The data contains 'boundary' events, indicating data discontinuities. Be cautious of filtering and epoching around these events.
  raw = mne.io.read_raw_eeglab(file_path, preload=True)
C:\Users\Nathaniel Byrd\AppData\Local\Temp\ipykernel_45480\417584291.py:7: RuntimeWarning: The data contains 'boundary' events, indicating data discontinuities. Be cautious of filtering and epoching around these events.
  raw = mne.io.read_raw_eeglab(file_path, preload=True)
C:\Users\Nathaniel Byrd\AppData\Local\Temp\ipykernel_45480\417584291.py:7: RuntimeWarning: The data contains 'boundary' events, indicating data discontinuities. Be cautious of filtering and epoching around these events.
  raw = mne.io.read_raw_eeglab(file_path, preload=True)
C:\Users\Nathaniel Byrd\AppData\Local\Temp\ipykernel_45480\417584291.py:7: RuntimeWarning: The data contains 'boundary' events, indicating data discontinuities. Be cautious of filtering and epoching around these events.
  raw = mne.io.read_raw_eeglab(file_path, preload=True)
C:\Users\Nathaniel Byrd\AppData\Local\Temp\ipykernel_45480\417584291.py:7: RuntimeWarning: The data contains 'boundary' events, indicating data discontinuities. Be cautious of filtering and epoching around these events.
  raw = mne.io.read_raw_eeglab(file_path, preload=True)
C:\Users\Nathaniel Byrd\AppData\Local\Temp\ipykernel_45480\417584291.py:7: RuntimeWarning: The data contains 'boundary' events, indicating data discontinuities. Be cautious of filtering and epoching around these events.
  raw = mne.io.read_raw_eeglab(file_path, preload=True)
C:\Users\Nathaniel Byrd\AppData\Local\Temp\ipykernel_45480\417584291.py:7: RuntimeWarning: The data contains 'boundary' events, indicating data discontinuities. Be cautious of filtering and epoching around these events.
  raw = mne.io.read_raw_eeglab(file_path, preload=True)
C:\Users\Nathaniel Byrd\AppData\Local\Temp\ipykernel_45480\417584291.py:7: RuntimeWarning: The data contains 'boundary' events, indicating data discontinuities. Be cautious of filtering and epoching around these events.
  raw = mne.io.read_raw_eeglab(file_path, preload=True)
C:\Users\Nathaniel Byrd\AppData\Local\Temp\ipykernel_45480\417584291.py:7: RuntimeWarning: The data contains 'boundary' events, indicating data discontinuities. Be cautious of filtering and epoching around these events.
  raw = mne.io.read_raw_eeglab(file_path, preload=True)
C:\Users\Nathaniel Byrd\AppData\Local\Temp\ipykernel_45480\417584291.py:7: RuntimeWarning: The data contains 'boundary' events, indicating data discontinuities. Be cautious of filtering and epoching around these events.
  raw = mne.io.read_raw_eeglab(file_path, preload=True)
C:\Users\Nathaniel Byrd\AppData\Local\Temp\ipykernel_45480\417584291.py:7: RuntimeWarning: The data contains 'boundary' events, indicating data discontinuities. Be cautious of filtering and epoching around these events.
  raw = mne.io.read_raw_eeglab(file_path, preload=True)
C:\Users\Nathaniel Byrd\AppData\Local\Temp\ipykernel_45480\417584291.py:7: RuntimeWarning: The data contains 'boundary' events, indicating data discontinuities. Be cautious of filtering and epoching around these events.
  raw = mne.io.read_raw_eeglab(file_path, preload=True)
C:\Users\Nathaniel Byrd\AppData\Local\Temp\ipykernel_45480\417584291.py:7: RuntimeWarning: The data contains 'boundary' events, indicating data discontinuities. Be cautious of filtering and epoching around these events.
  raw = mne.io.read_raw_eeglab(file_path, preload=True)
C:\Users\Nathaniel Byrd\AppData\Local\Temp\ipykernel_45480\417584291.py:7: RuntimeWarning: The data contains 'boundary' events, indicating data discontinuities. Be cautious of filtering and epoching around these events.
  raw = mne.io.read_raw_eeglab(file_path, preload=True)
C:\Users\Nathaniel Byrd\AppData\Local\Temp\ipykernel_45480\417584291.py:7: RuntimeWarning: The data contains 'boundary' events, indicating data discontinuities. Be cautious of filtering and epoching around these events.
  raw = mne.io.read_raw_eeglab(file_path, preload=True)
C:\Users\Nathaniel Byrd\AppData\Local\Temp\ipykernel_45480\417584291.py:7: RuntimeWarning: The data contains 'boundary' events, indicating data discontinuities. Be cautious of filtering and epoching around these events.
  raw = mne.io.read_raw_eeglab(file_path, preload=True)
C:\Users\Nathaniel Byrd\AppData\Local\Temp\ipykernel_45480\417584291.py:7: RuntimeWarning: The data contains 'boundary' events, indicating data discontinuities. Be cautious of filtering and epoching around these events.
  raw = mne.io.read_raw_eeglab(file_path, preload=True)
C:\Users\Nathaniel Byrd\AppData\Local\Temp\ipykernel_45480\417584291.py:7: RuntimeWarning: The data contains 'boundary' events, indicating data discontinuities. Be cautious of filtering and epoching around these events.
  raw = mne.io.read_raw_eeglab(file_path, preload=True)

,0,1,2,3,4,5,6,7,8,9,...,28490,28491,28492,28493,28494,28495,28496,28497,28498,28499
0,-33.71669,-25.14233,-10.50163,-15.47097,-14.63978,-18.08393,-12.67014,-15.45571,-14.11255,-14.50091,...,84.18697,80.65641,80.06675,75.86752,82.77135,80.00256,84.76408,78.21640,82.22863,80.90094
1,-13.54765,-12.98291,-12.86422,-15.47817,-14.47911,-13.76320,-12.89624,-12.01049,-10.87424,-16.25128,...,7.02716,-1.29402,-3.38745,1.53143,2.27372,5.82661,8.25260,-2.18277,0.87427,-0.91140
2,-1.38497,0.31020,-3.32693,2.74262,0.65681,3.07894,2.11051,8.90369,2.51776,15.54958,...,-33.55291,-42.94607,-40.40209,-30.88007,-41.59882,-27.98723,-48.22545,-37.61147,-25.23528,-24.16812
3,4.72390,0.14595,-1.53359,-2.63775,-2.02245,-3.02931,-5.37921,3.80315,1.64260,-4.99618,...,-4.49420,-10.81984,-1.52989,-13.28437,-3.82053,-12.72903,-3.61151,-15.83320,-15.15338,-9.96890
4,-19.37965,-20.68426,-38.11781,-33.88900,-24.81949,-22.95933,-23.72523,-22.19192,-16.93681,-26.68461,...,-24.00332,-17.60856,-20.98037,-31.88200,-19.49762,-25.89968,-23.27293,-27.04842,-21.93561,-26.03434
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
60,16.89617,17.68295,6.53693,9.89378,6.56455,9.07798,6.84313,11.80761,6.79411,5.97785,...,47.90747,52.34312,42.99758,51.76135,51.32692,54.57663,48.94542,56.31538,56.09702,55.13913
61,6.80970,11.50893,12.93351,10.05573,19.14054,16.08621,20.03481,17.90847,17.39329,22.08790,...,77.02309,58.68071,58.34769,64.96092,74.14655,70.43506,73.68684,59.33348,60.13338,66.78571
62,7.19965,9.41171,8.98145,9.50233,8.25897,7.92397,9.92945,6.79672,12.52182,4.70932,...,-4.03921,-4.14888,-8.49620,-4.09239,-9.86116,-3.76634,-11.80896,-8.72896,-7.83569,-7.65694
63,9.48901,6.86158,0.51682,4.09449,-0.50116,-0.64996,-7.77327,-4.64922,-0.22925,-9.15162,...,-41.80925,-16.39761,-17.05480,-11.45128,-15.69099,-45.86976,-26.56222,-16.86770,-18.52457,-34.38878
64,-10.47222,-8.49627,-16.39453,-3.70747,-11.87369,-7.19889,-8.07156,-7.08942,-3.85510,-6.32273,...,-93.84235,-113.37106,-106.18769,-108.73975,-104.19922,-94.27433,-92.81706,-104.77531,-97.63705,-93.78616

In [58]:
openneuro_X.describe()

,0,1,2,3,4,5,6,7,8,9,...,28490,28491,28492,28493,28494,28495,28496,28497,28498,28499
count,65.00000,65.00000,65.00000,65.00000,65.00000,65.00000,65.00000,65.00000,65.00000,65.00000,...,65.00000,65.00000,65.00000,65.00000,65.00000,65.00000,65.00000,65.00000,65.00000,65.00000
mean,1.15722,1.36938,0.98121,0.98999,-0.07228,-0.18575,-0.58257,-0.42485,1.41361,-0.50536,...,0.86092,-1.69607,4.22766,-0.72407,0.47471,-0.12598,-0.07696,0.01118,-0.82506,-0.74538
std,16.74107,16.30589,15.82387,15.91099,15.27804,15.17601,15.98005,16.16158,17.42034,17.68862,...,36.49249,38.10298,39.08631,37.84625,38.18542,37.88195,37.06716,35.54060,34.95978,37.76772
min,-42.93982,-40.31626,-38.11781,-40.69867,-37.21032,-38.36616,-41.74374,-40.26200,-44.81393,-50.40699,...,-93.84235,-113.37106,-106.18769,-108.73975,-104.19922,-94.27433,-92.81706,-104.77531,-97.63705,-93.78616
25%,-7.49723,-6.55020,-6.64637,-7.54801,-8.56319,-7.33487,-9.23700,-11.76291,-7.63424,-9.85286,...,-23.21998,-22.75729,-21.59610,-22.44100,-19.49762,-25.89968,-26.56222,-25.03158,-21.93561,-24.16812
50%,2.85955,1.82712,2.37812,2.01720,0.55743,1.30184,0.66122,0.85761,1.64260,0.77027,...,3.28682,0.19899,7.06856,1.53143,1.50946,5.23995,1.89098,-1.81541,0.87427,0.98910
75%,8.46396,11.50893,8.98145,10.29853,8.23633,7.22407,8.87784,8.90369,8.43484,6.19324,...,25.53535,18.65911,31.32324,19.94766,23.51406,28.70412,20.85397,22.00671,21.08902,24.95797
max,42.82328,50.36889,35.23463,32.42381,39.29787,34.00508,33.88787,38.11740,47.85119,55.37695,...,84.18697,80.65641,93.70728,75.86752,85.30463,80.00256,84.76408,78.21640,82.22863,80.90094

In [50]:
labels_file_path = 'openneuro_data/participants.tsv'

openneuro_Y = pd.read_csv(labels_file_path, sep='\t')
openneuro_Y = openneuro_Y['Group'].iloc[:65]
openneuro_Y

0     A
1     A
2     A
3     A
4     A
     ..
60    C
61    C
62    C
63    C
64    C
Name: Group, Length: 65, dtype: object

In [57]:
openneuro_Y.describe()

count     65
unique     2
top        A
freq      36
Name: Group, dtype: object

## Kaggle Nigar-EEG

In [60]:
data_dir = 'kaggle_nigar_data'

kaggle_nigar_X = pd.DataFrame()
kaggle_nigar_Y = pd.Series(dtype='bool')

for directory in Path(data_dir).iterdir():
    for file in Path(directory).iterdir():
        data = pd.read_csv(file).iloc[:, :19]
        row = pd.Series(data.to_numpy().flatten()).iloc[:250*60]
        kaggle_nigar_X = pd.concat([kaggle_nigar_X, row.to_frame().T], ignore_index=True)
        if directory.name == '1-Healthy':
            kaggle_nigar_Y = pd.concat([kaggle_nigar_Y, pd.Series([False])], ignore_index=True)
        else:
            kaggle_nigar_Y = pd.concat([kaggle_nigar_Y, pd.Series([True])], ignore_index=True)

kaggle_nigar_X

,0,1,2,3,4,5,6,7,8,9,...,14990,14991,14992,14993,14994,14995,14996,14997,14998,14999
0,-2.97030,1.87700,-0.06873,-4.06090,5.94060,-13.19900,25.25300,13.86400,20.35400,15.82900,...,17.08500,22.77200,18.38200,21.58100,17.25900,24.75200,21.14500,17.17200,15.85400,7.79390
1,31.37300,29.06100,20.76400,21.21200,17.82200,14.07400,15.07500,7.00000,1.97770,-0.91954,...,17.00000,8.82350,4.78960,12.43100,7.07070,15.84200,3.97310,12.06000,-6.00000,4.84850
2,-5.94770,-8.80260,-9.34710,-13.06500,-4.95050,-17.15200,-10.16800,-17.91000,-10.41300,-13.59300,...,-26.19800,-5.94770,-1.03560,-4.19240,5.02510,-13.86100,-1.07200,-32.39100,-20.89600,-35.17500
3,11.58600,19.35300,12.36600,22.00000,19.80200,32.25600,26.13100,38.80600,32.44400,41.74800,...,-4.10770,6.73140,7.70230,3.03970,5.00000,4.95050,5.99330,17.08500,12.93500,27.68300
4,5.94060,3.81880,7.14780,11.16800,-0.99010,1.95290,1.01010,1.92370,6.82770,8.93270,...,12.06000,1.98020,6.73140,9.20960,6.09140,-9.90100,11.04400,-2.02020,14.85900,10.69200
5,48.51500,39.74100,29.82800,18.27400,18.90500,18.11400,25.12600,26.79900,24.94400,25.55600,...,11.05500,19.80200,15.46900,24.67400,17.25900,12.93500,15.08400,13.06500,14.85900,6.76240
6,11.82300,12.55700,20.76400,21.32000,21.89100,21.03900,21.00000,24.68600,23.25300,23.71100,...,1.99000,0.00000,4.78960,5.13890,4.06090,-0.99502,-3.08210,0.00000,0.92409,2.96300
7,-0.98039,4.78960,-4.19240,3.03030,-8.91090,-6.12790,-13.00000,-9.86930,-14.29000,-12.74200,...,15.92000,4.90200,4.78960,5.08590,8.08080,4.95050,8.01350,7.00000,11.69900,6.76240
8,1.99000,2.84790,3.03970,4.04040,-0.99010,3.99320,-7.03520,-4.02640,-16.28200,-14.71300,...,13.06500,3.98010,4.78960,5.11230,5.05050,8.91090,15.16100,12.06000,20.72600,19.29500
9,-12.74500,-12.68600,-11.40900,-9.09090,-10.83700,-8.10720,-3.01510,-5.97010,-3.78210,-4.81300,...,3.00000,2.94120,2.84790,-0.06873,0.00000,0.98522,4.95810,1.00500,9.95020,3.91030
10,-2.92680,-3.92910,-2.14160,-2.01010,1.98020,-0.06734,4.02010,9.00000,8.59400,12.87400,...,15.15200,5.85370,3.80030,13.40200,14.07000,21.78200,20.13500,25.12600,23.00000,27.55100
11,-0.99010,-3.94820,-1.09970,-5.07610,-0.99502,-1.07740,12.06000,14.85900,16.33200,26.53600,...,22.11100,8.91090,9.64400,5.08590,5.07610,5.97010,2.96300,8.04020,2.91870,7.71930
12,-5.82520,-3.94820,-12.44000,-12.00000,-10.83700,-14.13700,-13.00000,-13.86100,-10.31400,-12.61800,...,-19.06700,-13.59200,-11.71500,-15.53300,-15.00000,-10.83700,-15.14200,-13.00000,-14.85100,-11.25800
13,1.96080,2.84790,2.01390,-1.01010,-0.99010,-4.10770,-4.02010,-5.00000,-4.72090,-2.89000,...,-6.00000,-5.88240,-4.91910,-7.36110,-10.10100,0.00000,-6.12790,-4.02010,-2.00000,-3.76400
14,-3.00650,1.87700,-5.22340,-1.00500,-8.91090,-1.07200,-0.06734,-0.99502,-6.60320,-2.86180,...,8.97820,0.91503,1.87700,3.02410,-4.02010,-3.96040,-0.06700,-7.13800,2.98510,-2.79370
15,-11.71500,-0.06472,-13.54100,-16.00000,-18.81200,-15.21900,-18.09000,-19.90000,-15.17500,-18.44700,...,3.97310,-3.94820,-7.83170,-6.28670,-4.00000,-5.94060,1.95290,-2.01010,0.99502,-0.88889
16,11.82300,11.58600,3.05560,1.01520,2.98510,9.98320,8.00000,15.77600,13.59100,18.78500,...,8.95520,-4.92610,-2.97730,-5.27780,-6.09140,-1.99000,-0.06700,9.00000,13.79500,15.52300
17,-33.33300,-35.01600,-22.74900,-25.25300,-22.77200,-25.32000,-20.00000,-27.51600,-21.94600,-22.59400,...,8.95520,1.96080,-3.94820,4.05500,-8.08080,7.92080,8.01350,7.00000,4.83660,9.63320
18,-8.86700,-10.74400,-6.28670,-6.09140,-5.94060,-14.20900,-10.05000,-28.77900,-13.33300,-37.37300,...,3.01510,-3.94090,-6.86080,-2.14160,-9.13710,1.98020,-7.13800,5.02510,-6.00660,11.66700
19,-19.90000,-14.83700,-16.57000,-20.55800,-16.81400,-15.07500,-17.68600,-15.07500,-14.70600,-16.89800,...,2.97800,-11.94000,6.73200,-4.91910,6.04270,-11.88800,2.01010,-15.61300,6.03020,-14.70600
20,-17.64700,-17.54000,-13.47100,-13.13100,-11.82300,-15.14200,-14.07000,-16.91500,-12.43600,-9.69110,...,-3.00000,5.88240,11.58600,-5.22340,12.12100,-14.77800,8.97820,-14.07000,5.97010,-8.58970
21,7.80490,9.59740,8.22110,12.06000,0.99010,-1.07740,-5.02510,-12.00000,-8.46760,-10.77200,...,6.06060,2.92680,4.76650,2.00350,6.03020,4.95050,4.98320,3.01510,3.00000,1.01110
22,-7.76700,-2.00650,-6.25430,3.00000,-2.95570,4.95810,6.00000,12.87100,18.93100,21.52800,...,5.93330,-0.97087,-1.03560,0.96220,-4.00000,5.91130,1.94300,14.00000,15.84200,16.10100
23,-0.01526,-0.01526,-0.01526,-0.01526,-0.01526,-0.01526,-0.01526,-0.01526,-0.01526,-0.01526,...,-0.01526,-0.01526,-0.01526,-0.01526,-0.01526,-0.01526,-0.01526,-0.01526,-0.01526,-0.01526
24,-0.41199,-76.61555,-180.28534,-127.58068,-152.72755,-73.74685,-66.48356,-139.84894,-107.62188,-45.63973,...,37.12520,0.38148,82.47501,140.88655,106.98100,118.42527,60.59358,54.91722,108.20172,88.79225
25,-2.54063,-2.54063,-2.54063,-2.54063,-2.54063,-2.54063,-2.54063,-2.54063,-2.54063,-2.54063,...,-2.54063,-2.54063,-2.54063,-2.54063,-2.54063,-2.54063,-2.54063,-2.54063,-2.54063,-2.54063
26,-0.50355,-75.97467,-227.77142,-175.55505,-187.82330,-0.96132,14.99962,-177.32509,-134.63035,-43.50347,...,10.11673,0.13733,30.28916,24.67384,24.24659,53.57443,38.22385,34.04288,36.30121,20.18769
27,-0.04578,-15.06065,-33.24941,-28.51911,-21.68307,5.93576,18.41764,-31.11315,-18.96696,-5.81369,...,-7.15648,-0.65614,-100.14496,-268.63508,-210.58976,-224.50599,-23.17845,-8.46876,-209.73526,-172.96101
28,-0.74769,-132.24994,-289.17372,-243.70184,-253.13191,-50.79728,-15.91516,-218.79911,-197.31441,-79.30114,...,32.79164,-0.07630,5.47799,-65.65957,-51.86542,-42.16068,47.59289,91.59991,-36.57588,-27.48150
29,-0.01526,7.98047,-25.74197,-23.94141,-0.68666,22.72068,41.51980,-11.27642,-14.45029,13.93149,...,-33.12734,-0.80873,-147.05119,-317.58602,-255.23766,-269.24544,-45.42611,-21.40841,-232.01343,-208.08728
30,0.07630,24.12451,-8.98756,7.46166,7.58373,54.30686,66.54459,1.23598,26.38285,36.17914,...,8.95705,0.04578,24.55177,19.51629,9.68948,23.20897,27.23735,29.34310,-0.90028,20.21820
31,-2.54063,-2.54063,-2.54063,-2.54063,-2.54063,-2.54063,-2.54063,-2.54063,-2.54063,-2.54063,...,-2.54063,-2.54063,-2.54063,-2.54063,-2.54063,-2.54063,-2.54063,-2.54063,-2.54063,-2.54063
32,-2.54063,-2.54063,-2.54063,-2.54063,-2.54063,-2.54063,-2.54063,-2.54063,-2.54063,-2.54063,...,-2.54063,-2.54063,-2.54063,-2.54063,-2.54063,-2.54063,-2.54063,-2.54063,-2.54063,-2.54063
33,-2.54063,-2.54063,-2.54063,-2.54063,-2.54063,-2.54063,-2.54063,-2.54063,-2.54063,-2.54063,...,-2.54063,-2.54063,-2.54063,-2.54063,-2.54063,-2.54063,-2.54063,-2.54063,-2.54063,-2.54063
34,-2.54063,-2.54063,-2.54063,-2.54063,-2.54063,-2.54063,-2.54063,-2.54063,-2.54063,-2.54063,...,-2.54063,-2.54063,-2.54063,-2.54063,-2.54063,-2.54063,-2.54063,-2.54063,-2.54063,-2.54063
35,-2.54063,-2.54063,-2.54063,-2.54063,-2.54063,-2.54063,-2.54063,-2.54063,-2.54063,-2.54063,...,-2.54063,-2.54063,-2.54063,-2.54063,-2.54063,-2.54063,-2.54063,-2.54063,-2.54063,-2.54063
36,-2.54063,-2.54063,-2.54063,-2.54063,-2.54063,-2.54063,-2.54063,-2.54063,-2.54063,-2.54063,...,-2.54063,-2.54063,-2.54063,-2.54063,-2.54063,-2.54063,-2.54063,-2.54063,-2.54063,-2.54063
37,-2.54063,-2.54063,-2.54063,-2.54063,-2.54063,-2.54063,-2.54063,-2.54063,-2.54063,-2.54063,...,-2.54063,-2.54063,-2.54063,-2.54063,-2.54063,-2.54063,-2.54063,-2.54063,-2.54063,-2.54063
38,-2.54063,-2.54063,-2.54063,-2.54063,-2.54063,-2.54063,-2.54063,-2.54063,-2.54063,-2.54063,...,-2.54063,-2.54063,-2.54063,-2.54063,-2.54063,-2.54063,-2.54063,-2.54063,-2.54063,-2.54063
39,-2.54063,-2.54063,-2.54063,-2.54063,-2.54063,-2.54063,-2.54063,-2.54063,-2.54063,-2.54063,...,-2.54063,-2.54063,-2.54063,-2.54063,-2.54063,-2.54063,-2.54063,-2.54063,-2.54063,-2.54063
40,-2.54063,-2.54063,-2.54063,-2.54063,-2.54063,-2.54063,-2.54063,-2.54063,-2.54063,-2.54063,...,-2.54063,-2.54063,-2.54063,-2.54063,-2.54063,-2.54063,-2.54063,-2.54063,-2.54063,-2.54063
41,-2.54063,-2.54063,-2.54063,-2.54063,-2.54063,-2.54063,-2.54063,-2.54063,-2.54063,-2.54063,...,-2.54063,-2.54063,-2.54063,-2.54063,-2.54063,-2.54063,-2.54063,-2.54063,-2.54063,-2.54063
42,-2.54063,-2.54063,-2.54063,-2.54063,-2.54063,-2.54063,-2.54063,-2.54063,-2.54063,-2.54063,...,-2.54063,-2.54063,-2.54063,-2.54063,-2.54063,-2.54063,-2.54063,-2.54063,-2.54063,-2.54063
43,-2.54063,-2.54063,-2.54063,-2.54063,-2.54063,-2.54063,-2.54063,-2.54063,-2.54063,-2.54063,...,-2.54063,-2.54063,-2.54063,-2.54063,-2.54063,-2.54063,-2.54063,-2.54063,-2.54063,-2.54063
44,-0.01526,-0.01526,-0.01526,-0.01526,-0.01526,-0.01526,-0.01526,-0.01526,-0.01526,-0.01526,...,-0.01526,-0.01526,-0.01526,-0.01526,-0.01526,-0.01526,-0.01526,-0.01526,-0.01526,-0.01526
45,-2.54063,-2.54063,-2.54063,-2.54063,-2.54063,-2.54063,-2.54063,-2.54063,-2.54063,-2.54063,...,-2.54063,-2.54063,-2.54063,-2.54063,-2.54063,-2.54063,-2.54063,-2.54063,-2.54063,-2.54063
46,-2.54063,-2.54063,-2.54063,-2.54063,-2.54063,-2.54063,-2.54063,-2.54063,-2.54063,-2.54063,...,-2.54063,-2.54063,-2.54063,-2.54063,-2.54063,-2.54063,-2.54063,-2.54063,-2.54063,-2.54063
47,-2.54063,-2.54063,-2.54063,-2.54063,-2.54063,-2.54063,-2.54063,-2.54063,-2.54063,-2.54063,...,-2.54063,-2.54063,-2.54063,-2.54063,-2.54063,-2.54063,-2.54063,-2.54063,-2.54063,-2.54063
48,-2.54063,-2.54063,-2.54063,-2.54063,-2.54063,-2.54063,-2.54063,-2.54063,-2.54063,-2.54063,...,-2.54063,-2.54063,-2.54063,-2.54063,-2.54063,-2.54063,-2.54063,-2.54063,-2.54063,-2.54063
49,-0.01526,-0.01526,-0.01526,-0.01526,-0.01526,-0.01526,-0.01526,-0.01526,-0.01526,-0.01526,...,-0.01526,-0.01526,-0.01526,-0.01526,-0.01526,-0.01526,-0.01526,-0.01526,-0.01526,-0.01526
50,-0.10681,-69.68795,-22.62913,-12.10040,-32.73060,-37.49142,-31.54040,96.23865,339.62005,36.88106,...,51.40764,-0.04578,-24.00244,-22.35447,-1.66323,-14.11460,-17.07485,-15.51843,56.22950,163.43938
51,-0.10681,-39.41405,-12.25299,-10.05570,-22.75120,-35.01946,-46.34165,105.63821,279.07225,27.35943,...,-50.15640,-0.16785,-35.99603,-47.22667,-46.95201,-62.88243,-66.66667,-71.51904,77.19539,253.13191
52,0.32044,62.76036,46.67735,43.53399,64.89662,58.30472,80.82704,-102.34226,-339.46746,-8.98756,...,3.64691,-0.04578,-36.14862,-4.98970,1.96841,29.92294,14.90806,31.93713,-46.92149,-205.92050

In [61]:
kaggle_nigar_X.describe()

,0,1,2,3,4,5,6,7,8,9,...,14990,14991,14992,14993,14994,14995,14996,14997,14998,14999
count,53.00000,53.00000,53.00000,53.00000,53.00000,53.00000,53.00000,53.00000,53.00000,53.00000,...,53.00000,53.00000,53.00000,53.00000,53.00000,53.00000,53.00000,53.00000,53.00000,53.00000
mean,-0.92685,-6.29214,-15.41104,-11.83900,-12.86875,-2.77821,0.46602,-10.10569,-3.74290,-1.88863,...,2.39136,0.00417,-3.35760,-9.87454,-7.76213,-7.28046,1.77524,2.63282,-3.06736,-0.22108
std,10.99158,29.01356,56.14668,45.31073,48.77408,20.44478,22.33177,50.51506,85.86673,20.75446,...,15.33734,5.91429,29.11980,61.69917,49.08589,53.18373,18.46966,21.47038,49.31766,65.14110
min,-33.33300,-132.24994,-289.17372,-243.70184,-253.13191,-73.74685,-66.48356,-218.79911,-339.46746,-79.30114,...,-50.15640,-13.59200,-147.05119,-317.58602,-255.23766,-269.24544,-66.66667,-71.51904,-232.01343,-208.08728
25%,-2.54063,-3.94820,-9.34710,-9.09090,-8.91090,-6.12790,-5.02510,-11.27642,-10.41300,-8.98756,...,-2.54063,-2.54063,-2.54063,-2.54063,-2.54063,-2.54063,-2.54063,-2.54063,-2.54063,-2.54063
50%,-2.54063,-2.54063,-2.54063,-2.54063,-2.54063,-2.54063,-2.54063,-2.54063,-2.54063,-2.54063,...,-0.01526,-0.80873,-2.54063,-2.54063,-2.54063,-2.54063,-1.07200,-2.54063,-2.00000,-2.54063
75%,-0.01526,1.87700,-0.06873,-0.01526,-0.68666,-0.01526,4.02010,-0.01526,-0.01526,-0.01526,...,8.95705,0.91503,4.78960,3.03970,5.05050,4.95050,5.99330,8.04020,9.95020,7.79390
max,48.51500,62.76036,46.67735,43.53399,64.89662,58.30472,80.82704,105.63821,339.62005,41.74800,...,51.40764,22.77200,82.47501,140.88655,106.98100,118.42527,60.59358,91.59991,108.20172,253.13191

In [52]:
kaggle_nigar_Y

0     0
1     0
2     0
3     0
4     0
5     0
6     0
7     0
8     0
9     0
10    0
11    0
12    0
13    0
14    0
15    0
16    0
17    0
18    0
19    0
20    0
21    0
22    0
23    1
24    1
25    1
26    1
27    1
28    1
29    1
30    1
31    1
32    1
33    1
34    1
35    1
36    1
37    1
38    1
39    1
40    1
41    1
42    1
43    1
44    1
45    1
46    1
47    1
48    1
49    1
50    1
51    1
52    1
dtype: int64

In [56]:
kaggle_nigar_Y.describe()

count   53.00000
mean     0.56604
std      0.50036
min      0.00000
25%      0.00000
50%      1.00000
75%      1.00000
max      1.00000
dtype: float64

# State Save

In [62]:
dill.dump_module("session.pkl")

MemoryError: